### ISSUE TITLE
I get the message "Wygląda na to, że na tej stronie nie ma ofert" when there are both types of offers present

### ISSUE THREAD

**Issue by lepczynski** [piotrkochan/allegro-poszukiwacz-niepromowanych#1]
Hi Pikey,

it seems that something has changed (I think after allegro introduced "szukaj u jednego sprzedawcy") - now the plugin I like so much can't jump to non-promoted offers.

URL I used:
`https://allegro.pl/listing?string=Logitech%20H800&order=d&bmatch=baseline-cl-eyesa2-dict43-ele-1-2-0205`

Pressing the button produces a `Wygląda na to, że na tej stronie nie ma ofert` message.
I did make sure, there are both promoted and non-promoted offerts on that page.

Cheers,
Michał

**Comment by piotrkochan** [comment]
Hi @lepczynski, from time to time Allegro changes some aspects on their webpage, as from 0.2.0 which already awaiting chrome/ff/opera moderation it should be fixed.
